;;; octra.el --- A super light alternative to ~hydra~ which allows you to define the body everywhere. -*- lexical-binding: t -*-

;;; Commentary:
;; See README.org.

;;; Code:

(defun octra--keep-pred (map sticky foreign-key-leave foreign-key-warn foreign-key-drop)
  "The keep-pred used by octra in set-transient-map."
  (if (eq this-command 'keyboard-quit)
      nil	; Quitting the map
    (if (lookup-key map (this-single-command-keys))
	sticky	; Keep the map
      (when foreign-key-warn ; The key is foreign
	;; Warn the user
	(message "The key you have just pressed is not defined in the map.\nThe map will %s, and the key will %s."
		 (if foreign-key-leave "be deactivated" "keep activating")
		 (if foreign-key-drop "be ignored" "continue executing")))
      (when foreign-key-drop
	(setq this-command (lambda () "Does nothing." (interactive))))
      (not foreign-key-leave))))

(defun octra-use-map (map &optional sticky foreign-key-leave foreign-key-warn foreign-key-drop)
  "Like `octra-use', but accept a map instead of generate one."
  (set-transient-map map (lambda () (octra--keep-pred map sticky foreign-key-leave foreign-key-warn foreign-key-drop))))

(defun octra-use (map-alist &optional sticky foreign-key-leave foreign-key-warn foreign-key-drop)
  "Activate a transient map generated by MAP-ALIST.

MAP-ALIST should be an alist where each item has structure
\(KEY . COMMAND) where KEY is a key sequence acceptable by `keymap-set'
and COMMAND is a command going to be binded to KEY.

If STICKY is non-nil, the map will not be deactivated after first
keystroke.

The three arguments started with FOREIGN-KEY decides what to do when a
foreign key (i.e. a key sequence that is not in MAP-ALIST) is
pressed.  When FOREIGN-KEY-LEAVE is non-nil, the map will be deactivated;
when FOREIGN-KEY-WARN is non-nil, the user will be warned about the
key not in the map; when FOREIGN-KEY-DROP is non-nil, the key will be
blocked from executing corresponding command.

Returns a function that will deactivate the map."
  (let ((map (make-sparse-keymap)))
    (dolist (map-item map-alist)
      (keymap-set map (car map-item) (cdr map-item)))
    (octra-use-map map sticky foreign-key-leave foreign-key-warn foreign-key-drop)))

(defun octra-bind (map-alist &optional sticky foreign-key-leave foreign-key-warn foreign-key-drop)
  "Like `octra-use', but return a function to activate instead of activate it right away.

You may want to use this in your key binding."
  (let ((map (make-sparse-keymap)))
    (dolist (map-item map-alist)
      (keymap-set map (car map-item) (cdr map-item)))
    (lambda () "Generated by octra-bind." (interactive)
      (octra-use-map map sticky foreign-key-leave foreign-key-warn foreign-key-drop))))

(provide 'octra)

;;; octra.el ends here
